image:
  tag: "{{ image_tag }}"
  repository: "{{ docker_repo }}/api-gateway"

env:
  HCX_API_BASEPATH : http://hcx-api.{{ env }}.svc.cluster.local:8080
  REGISTRY_BASE_PATH : http://hcx-registry.{{ env }}.svc.cluster.local:8081
  REDIS_HOST : redis-master.{{ env }}.svc.cluster.local
  REDIS_PORT : 6379
