job_classname: "org.swasth.dp.claims.task.ClaimsStreamTask"
taskManagerAdditionalArgs: []
  # For example
  # - -Dfs.azure.account.key.myblobstorageaccount.blob.core.windows.net=myblobstorageaccountpassword,
jobManagerAdditionalArgs: []
  # For example
  # - -Dfs.azure.account.key.hcxapi.blob.core.windows.net=mysupersecretpassword

