image:
  tag: "{{ image_tag }}"
  repository: "{{ docker_repo }}/hcx-registry"

env:
  connectionInfo_uri :  "jdbc:postgresql://{{ hcx_registry_postgresql_host }}/registry"
  connectionInfo_username : "{{hcx_registry_postgresql_user}}"
  connectionInfo_password : "{{ hcx_registry_postgresql_password  }}"
  sunbird_sso_url : "{{ sunbird_sso_url }}"
  sunbird_sso_realm : swasth-health-claim-exchange
  sunbird_sso_client_id : client
  sunbird_sso_admin_client_id : admin-api
  sunbird_sso_admin_client_secret : "{{ sso_admin_client_secret }}"
  search_providerName : io.opensaber.registry.service.ElasticSearchService
  elastic_search_enabled : true
  elastic_search_connection_url : "{{groups['elasticsearch'][0]}}:9200"
  signature_enabled: false
  claims_url : http://localhost:8082
