image:
  tag: "{{ image_tag }}"
  repository: "{{ docker_repo }}/hcx-onboard"
env:
  es_host: "{{ groups['elasticsearch'][0] }}"
  audit_index: "hcx_audit"
  audit_alias: "hcx_audit"
  registry_basePath: "http://hcx-registry.{{ env }}.svc.cluster.local:8081"
  registry_hcxcode: "{{ registry_hcx_code }}"
  not_allowed_urls: {{ gateway_not_allowed_urls }}
  hcx_instance_name: {{ hcx_instance_name }}
  aws_accessKey: "AKIA6I75KJYE2AIRJ24B"
  aws_accessSecret: "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"
  aws_region: "ap-southeast-1"

service:
  type: LoadBalancer
  port: 8082
