image:
  tag: "{{ image_tag }}"
  repository: "{{ docker_repo }}/hcx-onboard"
env:
  es_host: "{{ groups['elasticsearch'][0] }}"
  audit_index: "hcx_audit"
  audit_alias: "hcx_audit"
  registry_basePath: "http://hcx-registry.{{ env }}.svc.cluster.local:8081"
  registry_hcxcode: "{{ registry_hcx_code }}"
  not_allowed_urls: {{ gateway_not_allowed_urls }}
  hcx_instance_name: {{ hcx_instance_name }}
  aws_accessKey: "AKIAQPEQMNBRMBH7HZN4"
  aws_accessSecret: "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"
  aws_region: "ap-southeast-1"
  postgres_url: "jdbc:postgresql://{{ hcx_api_postgresql_host }}/postgres"
  postgres_user: "{{ hcx_api_postgresql_user }}"
  postgres_password: "{{ hcx_api_postgresql_password }}"
  HCX_API_BASEPATH : http://hcx-api.{{ env }}.svc.cluster.local:8080
  

service:
  type: LoadBalancer
  port: 8082
