env: dev
docker_repo: swasth2021
keycloak_postgresql_host: ""
keycloak_postgresql_user: ""
# Ref: https://www.middlewareinventory.com/blog/ansible-get-ip-address/
elasticsearch_network_host: "hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]"

kafka_topics:
  - "{{ env }}.hcx.audit"
  - "{{ env }}.hcx.request.claim"
  - "{{ env }}.hcx.request.coverageeligibility"
  - "{{ env }}.hcx.request.ingest"
  - "{{ env }}.hcx.request.payload"
  - "{{ env }}.hcx.request.payment"
  - "{{ env }}.hcx.request.preauth"
  - "{{ env }}.hcx.request.retry"
  - "{{ env }}.hcx.request.search"
