---
# defaults file for helm_deploy
secor_jobs:
  raw-telemetry-backup:
    replicas: 1
    consumer_group: "{{env}}.telemetry.raw.backup"
    service_name: "raw_telemetry_backup"
    base_path: "raw"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{env}}.telemetry.raw"
    kafka_broker_host: "{{ groups['kafka']|join(',') }}"
    zookeeper_quorum: "{{ groups['zookeepers']|join(':2181,')}}:2181"
    max_file_size: 100000000
    max_file_age: 14400
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    message_channel_identifier: ""
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
    storage:
      size: 10Gi
    requests:
      cpu: 100m
      memory: 100Mi
    lag_threshold_warning: 50000
    lag_threshold_critical: 100000
