# name: Deploy worflow for HCX applications.

# on:
#   push:
#     branches:
#       - main
#       - sprint-*
#       - workflow
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     env:
#       AWS_REGION: ap-south-1
#       CLUSTER_NAME: dev-cluster
#     steps:
#       - uses: actions/checkout@v2

#       - name: AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}
#           aws-profile: git-deploy
#           #role-to-assume: arn:aws:iam::131795456882:role/OrganizationAccountAccessRole
#           # #role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/OrganizationAccountAccessRole
#           # role-session-name: ci-run-${{ github.run_id }}
          
      
#       # - name: kubeconfig
#       #   run: |
#       #     aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
#       #     echo "KUBE_CONFIG_DATA=$(cat ~/.kube/config | base64)" >> $GITHUB_ENV

#       # - name: echo_kubeconfig
#       #   run: |
#       #     echo ${{ secrets.KUBE_CONFIG_DATA }}

#       # - name: checkout private
#       #   uses: webfactory/ssh-agent@v0.6.0
#       #   with:
#       #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       # - name: checkout private
#       #   uses: actions/checkout@v2
#       #   with:
#       #       repository: https://github.com/Swasth-Digital-Health-Foundation/DevOps
#       #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: helm deploy
#         uses: deliverybot/helm@v1.5.0
#         env:
#           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#         with:
#           #plugins: "https://github.com/jkroepke/helm-secrets" # optional
#           #command: helm secrets upgrade <release name> --install --wait <chart> -f <path to values.yaml>
#           command: helm upgrade --install api-gateway   --wait ../../application/helm/core/api-gateway/ -f ${{ env.PRIVATE_REPO }}/hcx/ansible/inventory/dev/values.yaml --namespace dev

name: Deploy
on:
  push:
    branches:
      - main
      - sprint-*
      - workflow
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'headout/helm@master'
      with:
        release: 'nginx'
        namespace: 'default'
        chart: 'app'
        token: '${{ github.token }}'
        values: |
          name: foobar
        version: helm3
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'