name: Deploy worflow for HCX applications.

on:
  push:
    branches:
      - main
      - sprint-*
      - workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-south-1
      CLUSTER_NAME: dev-cluster
    steps:
      - uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          aws-profile: git-deploy

      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'api-gateway'
          namespace: 'dev'
          chart: '--wait ../../application/helm/core/api-gateway'
          token: '${{ github.token }}'
          # values: 
          value-files: "${{ env.PRIVATE_REPO }}/hcx/ansible/inventory/dev/values.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
