name: Newman Test Run
on:
  push:
    branches:
    - master
    - staging
    - workflow
# env:
#   CI: false
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1


      - name: Checkout private
        uses: actions/checkout@v3
        with:
          # repository: Swasth-Digital-Health-Foundation/DevOps
          repository: Swasth-Digital-Health-Foundation/DevOps
          ref: 'workflow'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: recursive
          path: DevOps
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
          # collectionID: 7596548-a3da24e1-d5f8-48b2-9301-3a71cc9d204a
          # environmentID: 17596548-3fe923e0-c5ce-4eea-a943-339b28b01a22
      - run: npm install -g newman
        # env:
        #  CI: false
      - run: npm install -g newman-reporter-htmlextra
      #- run: newman run "https://api.getpostman.com/collections/7596548-a3da24e1-d5f8-48b2-9301-3a71cc9d204a?apikey=PMAT-01GQF54HSA7E1B8YMK338380QZ" --environment "https://api.getpostman.com/environments/17596548-3fe923e0-c5ce-4eea-a943-339b28b01a22?apikey=PMAT-01GQF54HSA7E1B8YMK338380QZ"
      # - run: newman run application/pipelines/deploy/newman/collection.json -e DevOps/hcx/ansible/inventory/${{ github.event.inputs.environment }}/newman/environment.json -r htmlextra --reporter-htmlextra-export /tmp/newman.html
      - run: newman run application/pipelines/deploy/newman/collection.json -e DevOps/hcx/ansible/inventory/dev/newman/environment.json -r htmlextra --reporter-htmlextra-export /tmp/newman.html
      # - run: newman run application/pipelines/deploy/newman/collection.json -e DevOps/hcx/ansible/inventory/dev/newman/environment.json
        continue-on-error: true
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload-file-path: "/tmp/newman.html"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
